DROP TABLE IF EXISTS stat_entity;

CREATE TABLE IF NOT EXISTS stat_entity
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       varchar(50),
    uri       varchar(50),
    ip        varchar(20),
    timestamp timestamp
);